### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by lennard7001** [andreybutenko/uno#4]
Do you still update this repo, or can it be forked and developed elsewhere?

**Comment by andreybutenko** [comment]
I'm not actively working on it, but you can definitely leave issues or submit PRs if you'd like changes :)

It's open-source under the Apache License 2.0. [Here is a human-readable explanation of the Apache License 2.0](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0))

You can definitely fork and develop it elsewhere as long as you comply with the license, I'd love to hear about what you end up doing! :)
